[workspace]
authors = ["Yanting Liu <ytl_cc@hotmail.de>"]
channels = ["conda-forge"]
name = "2025_12-markov-english"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.8,<4"
numpy = ">=2.3.5,<3"
seaborn = ">=0.13.2,<0.14"
ipykernel = ">=7.1.0,<8"
jieba = ">=0.42.1,<0.43"
